# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dshare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
   use_frameworks!

  # Pods for Firesearch
  pod 'Firebase/Core'

  # Pods for Dshare

  target 'DshareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DshareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
